version: '3'

networks:
  default:
    external:
      name: bridge

services:
  nginx:
    image: mirror.gcr.io/nginx:stable
    restart: always
    hostname: "${COMPOSE_PROJECT_NAME}.test.deltabook.ru"
    environment:
      - "VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.test.deltabook.ru"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/deltabook/current
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    network_mode: bridge
    links:
      - php

  php:
    build: ./docker/php
    entrypoint: /bin/sh /var/www/deltabook/current/docker/php/entrypoint.sh
    restart: always
    volumes:
      - .:/var/www/deltabook/current
      - ./docker/logs/php:/var/www/scripts/log/
      - ./docker/logs/php:/var/log/php/
      - ./docker/logs/php:/root/.npm/_logs
    extra_hosts:
      - ""
    environment:
      - ENV_TYPE=Testing
    network_mode: bridge
    links:
      - mail

  mail:
    restart: always
    image: catatnight/postfix
    volumes:
      - ./docker/mail/main.cf:/etc/postfix/main.cf
    network_mode: bridge
