version: '3'

services:

  memcached:
    container_name: "${COMPOSE_PROJECT_NAME}.memcached"

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}.nginx"
    hostname: "${COMPOSE_PROJECT_NAME}.test.labsvr.ru"
    environment:
      - "VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.test.labsvr.ru"

  php:
    container_name: "${COMPOSE_PROJECT_NAME}.php"

  mail:
    container_name: "${COMPOSE_PROJECT_NAME}.mail"
