FROM ubuntu:18.04

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get clean \
    && apt-get -y update \
    && apt-get install -y locales ssmtp curl software-properties-common git apt-utils apt-transport-https zip unzip

# install mssql drivers
#RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
#RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
#RUN apt-get update

#install php
RUN locale-gen en_US.UTF-8
RUN LC_ALL=en_US.UTF-8 \
    add-apt-repository ppa:ondrej/php

RUN apt-get update
RUN apt-get -y install \
    php8.1 \
    php8.1-dev \
    php8.1-fpm \
    imagemagick \
    php-imagick \
    php-ssh2 \
    php-pear \
    php-mongodb \
    php-memcached \
    php8.1-bcmath \
    php8.1-bz2 \
    php8.1-curl \
    php8.1-gd \
    php8.1-mbstring \
    php8.1-mcrypt \
    php8.1-mysql \
    php8.1-odbc \
    php8.1-xsl \
    php8.1-zip \
    php8.1-intl

#RUN pecl install mongodb
#RUN apt download php-memcache && apt download php-memcache  && dpkg -i php-mem*.deb && service php8.1-fpm restart

#RUN pecl install redis \
#	&& echo "extension=redis.so" > /etc/php/8.1/fpm/conf.d/redis.ini \
#	&& echo "extension=redis.so" > /etc/php/8.1/cli/conf.d/redis.ini

RUN sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml

# install php sqlsrv, pdosqlsrv
RUN apt-get install unixodbc-dev -y
RUN pecl install sqlsrv pdo_sqlsrv \
	&& echo "extension=sqlsrv.so" > /etc/php/8.1/fpm/conf.d/sql-srv-php.ini \
	&& echo "extension=sqlsrv.so" > /etc/php/8.1/cli/conf.d/sql-srv-php.ini \
	&& echo "extension=pdo_sqlsrv.so" > /etc/php/8.1/fpm/conf.d/pdo-sql-srv-php.ini \
	&& echo "extension=pdo_sqlsrv.so" > /etc/php/8.1/cli/conf.d/pdo-sql-srv-php.ini

# Microsoft ODBC Driver for SQL Server
RUN DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get install -y msodbcsql18
RUN DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get install -y mssql-tools18

RUN pecl install xdebug \
	&& echo "zend_extension=xdebug.so" > /etc/php/8.1/fpm/conf.d/xdebug-php.ini \
	&& echo "zend_extension=xdebug.so" > /etc/php/8.1/cli/conf.d/xdebug-php.ini

RUN cd /tmp \
 	&& git clone https://github.com/tideways/php-xhprof-extension.git tideways \
 	&& cd tideways \
 	&& phpize \
	&& ./configure \
	&& make \
	&& make test \
	&& make install \
	&& echo "extension=tideways_xhprof.so" > /etc/php/8.1/cli/conf.d/tideways-php.ini \
	&& echo "extension=tideways_xhprof.so" > /etc/php/8.1/fpm/conf.d/tideways-php.ini \
	&& rm -rf /tmp/tideways

RUN rm /etc/alternatives/php && ln -s /usr/bin/php8.1 /etc/alternatives/php

#install node & npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -yqq \
	&& apt-get install -y yarn \
	&& yarn global add gulp

#php stuff composer, deployer etc
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

RUN curl -LO https://phar.phpunit.de/phpdcd.phar \
    && mv phpdcd.phar /usr/local/bin/phpdcd \
    && chmod +x /usr/local/bin/phpdcd

RUN curl -LO https://phar.phpunit.de/phploc.phar \
    && mv phploc.phar /usr/local/bin/phploc \
    && chmod +x /usr/local/bin/phploc

RUN curl -LO https://pdepend.org/static/latest/pdepend.phar \
    && mv pdepend.phar /usr/local/bin/pdepend \
    && chmod +x /usr/local/bin/pdepend

RUN curl -LO https://phar.phpunit.de/phpcpd.phar \
    && mv phpcpd.phar /usr/local/bin/phpcpd \
    && chmod +x /usr/local/bin/phpcpd

RUN curl -LO https://deployer.org/deployer.phar \
    && mv deployer.phar /usr/local/bin/dep \
    && chmod +x /usr/local/bin/dep

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 9000
EXPOSE 9002

CMD ["php-fpm8.1", "-F"]